Update style 358
Kozea/www-pellov pull request #19
Opened 2021-11-30 08:57 UTC by annabellou

Voici la pull request pour les divers changement de style du site de Promomaker selon le ticket https://github.com/Kozea/pellov/issues/358.

J'ai retiré pas mal de style inutilisé et réécrit certaines parties de HTML (c'était plus simple de repartir de 0 que de chercher dans tous les bouts de code les choses à modifier pour arriver au bon résultat).

Par contre j'ai un doute sur l'utilisation de la bonne nomenclature concernant le lien de la page `legal.html` (ligne 352 de `index.html`) : je n'ai pas réussi / compris comment utiliser les même types de liens que dans le reste du site, du coup j'ai juste mis un lien "classique"…

Bonne lecture ! 🧐

2021-11-30 09:28 UTC, gentooboontoo requested changes
* Apparemment il y a un `nowrap` qui traîne :

![2021-11-30_10-27](https://user-images.githubusercontent.com/137324/144020497-22cebf69-fe31-4d2e-8700-768c670ea4b0.png)

* Si jamais on veut de la perfection :wink: : 

![2021-11-30_10-29](https://user-images.githubusercontent.com/137324/144020871-a9b07199-48fc-4d9d-96a6-f5221b335ae7.png)

* Si jamais on veut de la perfection 2 : 

![2021-11-30_10-30](https://user-images.githubusercontent.com/137324/144021003-c0b0ad1a-fb07-42e6-a89c-886db5021e8a.png)

2021-11-30 15:37 UTC, gentooboontoo requested changes
Première passe effectuée.

2021-11-30 15:37 UTC, gentooboontoo commented on static/stylesheets/styles.css
> +  /* top: 100px; */
Code commenté oublié dans le CSS (à divers endroits)

2021-12-02 18:01 UTC, gentooboontoo approved these changes

2021-12-03 14:20 UTC, annabellou commented on static/stylesheets/styles.css
> +  /* top: 100px; */
Le code commenté oublié a été supprimé.

2021-12-03 14:21 UTC, annabellou commented
@gentooboontoo tu as approuvé la pull request un peu tôt, il me restait encore la partie sur l'amélioration du formulaire de contact et la suppression du code commenté 😆
Les 2 choses sont faites désormais !

2021-12-03 17:41 UTC, gentooboontoo commented
> @gentooboontoo tu as approuvé la pull request un peu tôt

Oups ^^, j'avais oublié ces points. Je n'ai regardé que ce qui avait changé effectivement.

2021-12-06 10:07 UTC, merged